name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:

jobs:
  generate:
    name: Generate snake animation
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake game from GitHub contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: valdirjunior011
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake game to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
